### ISSUE TITLE
[PD] Creating a Cover Letter

### ISSUE THREAD

**Issue by kayali436** [kayali436/Coursework-Planner-CYF#230]
From Module-React created by [LaraHuzjan](https://github.com/LaraHuzjan): CodeYourFuture/Module-React#29  

### Coursework content

Create a cover letter for a job vacancy 250 words long. Share it on the #cyf-profile-review and ask for feedback. 

When writing, follow the CYF cover letter criteria that can be found in the cyf-profile-review channel.  

For extra help watch the videos bellow. Use constructive criticism when watching them and keep in mind some information might differ from criteria CYF has. When/if that occurs, follow the latter.   

[How To Write an Amazing Cover Letter for Developer Jobs](https://www.youtube.com/watch?v=jB9XQXespos ) 
[Write an Amazing Cover Letter: 3 Golden Rules](https://www.youtube.com/watch?v=NUhDP30IRKk ) 
[Why Your Cover Letter Gets Rejected](https://www.youtube.com/watch?v=xudcyY06PiI)

### Estimated time in hours

2

### What is the purpose of this assignment?

Your cover letter complements your CV by making it easy for the employer to see how your experience and interest connect to the position. Your goal is to convince the employer to interview you. Learning how to write a cover letter will increase your chances of finding a job.

### How to submit

- Write your Cover Letter
- Review it with Grammarly
- Post it on the Screenshot of the #cyf-profile-review Slack channel
- Post the feedback you get on your CV in the #cyf-profile-review and post it under your ticket for review.

**Comment by kayali436** [comment]
![Image](https://github.com/kayali436/Coursework-Planner-CYF/assets/79542167/060adaaf-334f-45c1-88fc-d0900de2a6ae)

**Comment by kfklein15** [comment]
You had good feedback of your peers on your Cover letter. A couple of points for me:
- make enough changes so it feels like you are writing it, that feels like you telling your story, if you haven't done it. Just felt a bit on the robotic side, but that could be just my impression
- be more specific about WHY they should hire you. If they skim through your CV, you must be the perfect candidate for that vacancy.
- 
Please close this ticket and move it to done.
