### ISSUE TITLE
[PD] Cover letter tips

### ISSUE THREAD

**Issue by kayali436** [kayali436/Coursework-Planner-CYF#250]
From Module-React created by [esma-g](https://github.com/esma-g): CodeYourFuture/Module-React#22  

### Coursework content

Write 3 bullet points for the top tips you learned so far about cover letters. Share them in a thread on Slack. Create the post for the thread if it hasn't been created yet.

### Estimated time in hours

0.5

### What is the purpose of this assignment?

This assignment aims to help you consolidate your understanding of cover letter writing and the most important points to pay attention to while writing a cover letter.

It is also an opportunity to write phrases in English, so try to avoid using AIs to write them for you (use them to get ideas instead, if you get stuck). Remember to check your grammar.

### How to submit

- Share your tips in a thread on Slack. Create the post for the thread if it hasn't been created yet.
- Add a screenshot of your Slack message on this ticket.
- Copy and paste the content you added to Slack on this ticket.
- Make sure you have no grammar, spelling, punctuation mistakes.

**Comment by kayali436** [comment]
- Tailor each cover letter to the specific job and company to demonstrate your genuine interest and alignment with their needs.

- Use clear and concise language to highlight your relevant skills, experiences, and achievements that make you a strong candidate for the position.

- Address the hiring manager by name if possible and showcase your enthusiasm for the opportunity while expressing gratitude for their consideration.

**Comment by kayali436** [comment]
![Image](https://github.com/kayali436/Coursework-Planner-CYF/assets/79542167/2bf2252c-6518-4808-b5be-ba2c60354616)

**Comment by kfklein15** [comment]
Excellent. Please close this ticket and move it to done.
