### ISSUE TITLE
[PD] Developers daily activities

### ISSUE THREAD

**Issue by kayali436** [kayali436/Coursework-Planner-CYF#27]
From Course-Fundamentals created by [kfklein15](https://github.com/kfklein15): CodeYourFuture/Course-Fundamentals#26  

### Coursework content

Research a developer's daily **activities** and **behaviours**. What will you expect to know or do when you get your first job?

Activities are specific actions, tasks, or operations to accomplish a particular goal or objective.
- For example: A marketing analyst must conduct market research and data analysis to identify consumer trends

Behaviour is the observable actions, reactions, or conduct of someone.
- For example: A marketing analyst must be able to effectively communicate complex data clearly and understandably to stakeholders. 

### Estimated time in hours

1

### What is the purpose of this assignment?

- [x] Research a developer's daily activities and behaviours 
- [x] Write at least 50 words on a Google Docs file
- [x] Check the grammar using an available too, for example, Grammarly
- [x] Share the file with your cohort on the "Developers daily activities" thread. If the thread doesn't exist yet, create it.
- [x] Read two contents shared with you
- [x] Leave at least 2 comments or questions on each text you read

### How to submit

Add the link to your Google Docs
Add a screenshot of your post sharing your coursework

**Comment by kayali436** [comment]
https://docs.google.com/document/d/1Uap2DsbQ7wo51TLPbisa3dNzylc1VVpn0ucR9ysOgtY/edit?usp=sharing

**Comment by kayali436** [comment]
![Image](https://github.com/kayali436/Coursework-Planner-CYF/assets/79542167/ec0e40d1-fa5a-4085-a1bc-0419070a0362)

**Comment by kfklein15** [comment]
Simple and clear. Well done.

Make sure you review your English texts with a grammar tool.
- Software developer is **A** professional in charge of coding and designing **softw**are for businesses and consumers.

Other suggestions:
- "Users" instead of "consumers", which is a more tech industry language

AI checker: only 16%
