### ISSUE TITLE
[PD] Organise a study session about Time Management tools

### ISSUE THREAD

**Issue by kayali436** [kayali436/Coursework-Planner-CYF#29]
From Course-Fundamentals created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/Course-Fundamentals#12  

### Coursework content

Organise a study session with the pair you were assigned to during class - check out the Google Sheet.

Think about how you manage your time and which tools you use (add some examples and suggestions from our side). If you still need to start using them, research some and bring them to this meeting. 

### Estimated time in hours

2

### What is the purpose of this assignment?
- [x] Understand how you and your pair organise your time
- [x] Identify at least 2 time management tools each
- [x] With your pair, write a short paragraph about your findings
- [x] Share your findings in the "Time Management Tools" thread on your cohort Slack Channel. _Search for it on the channel. If the thread is not yet available, you can create it_
- [x] Read your peers text and react to it the the appropriate emoji

### How to submit
Add the link to your post on Slack on this coursework
Add a screenshot of your post on this coursework

**Comment by kayali436** [comment]
https://docs.google.com/document/d/1GZQicTdOAXI661ujjXiKJaBefqo8X5-KdYAK21QDcWI/edit?usp=sharing




![Image](https://github.com/kayali436/Coursework-Planner-CYF/assets/79542167/e4387c48-0864-40a2-a940-827f96267da5)

**Comment by kfklein15** [comment]
I liked the approach of talking about long-term planning, but the goal here was to focus more on your daily/weekly/monthly time management, which you will need for your life.

You also should have discussed 2 time management tools, but you just did one. Again, not achieving the acceptance criteria for this ticket. 

Make sure you check your text with Grammarly or similar. Some examples below:
- There **ARE** many simple methods of 

And the Master List in your developer life will be your Backlog.

AI checker: 40% possibly written by AI.
